
### 3. **Arquivo `publish-to-pypi.yml`**:
Este arquivo está configurado corretamente para o GitHub Actions, mas há uma pequena omissão no bloco de código de instalação das dependências. Você precisa corrigir o final para garantir que ele checa a existência do arquivo `requirements.txt`.

```yaml
name: Publish Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Build package
      run: |
        python setup.py sdist bdist_wheel

    - name: Verify build
      run: |
        python -m pip install twine
        twine check dist/*

    - name: Publish package
      env:
        TWINE_USERNAME: ${{ secrets.TEST_PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD }}
      run: |
        twine upload --repository-url https://test.pypi.org/legacy/ dist/*
